services:
  gdrive-backup:
    restart: always
    image: gdrive-backup:latest
    env_file:
      - .env
    volumes:
      - ${SYNC_FOLDER}:/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
