services:
  prominence2rpg:
    restart: always
    image: p2rpg
    ports:
      - 25565:25565
    env_file:
      - .env
    volumes:
      - ./server:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
