services:
  prominence2rpg:
    restart: always
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    env_file:
      - .env
    volumes:
      - ./p2-data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
